# Generated by Django 5.2.6 on 2025-10-06 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactions", "0003_initial"),
        ("recipes", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Favourite",
            new_name="Favorite",
        ),
        migrations.RemoveConstraint(
            model_name="favorite",
            name="interactions_favourite_unique_relationships",
        ),
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"),
                name="interactions_favorite_unique_relationships",
            ),
        ),
    ]
