# Generated by Django 5.2.6 on 2025-10-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_remove_user_confirmation_code_alter_user_avatar_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ("following",),
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
